site_name: Tài liệu SQL và Dataset
theme:
  name: material
  language: vi
  favicon: assets/site/favicon.ico
  logo: assets/site/brand.png
  palette:
    primary: teal
    accent: amber
  features:
    - navigation.footer
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences